version: '3'
services:
  web:
    ports:
      - 3000:3000
    links:
      - pg
    # For using pry
    stdin_open: true
    tty: true

  pg:
    ports:
      - 5432:5432

  webpack:
      ports:
        - 8080:8080
