version: '3'
services:
  ci:
    build:
      context: .
      dockerfile: ./docker/ci/Dockerfile
    links:
      - pg
    env_file: .env
    tty: true

  pg:
    build:
      context: .
      dockerfile: ./docker/pg/Dockerfile
    env_file: .env
    ports:
      - "5432:5432"