version: '3'
services:
  pg:
    build:
      context: .
      dockerfile: ./docker/pg/Dockerfile
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./:/home/dockeruser/project
      - backend-modules:/usr/local/bundle
    env_file: .env

  webpack:
    build:
      context: .
      dockerfile: ./docker/webpack/Dockerfile
    volumes:
      - ./:/home/dockeruser/project
      - backend-modules:/usr/local/bundle
    env_file: .env


volumes:
  backend-modules:
    external:
      name: backend-modules