version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/piter_lowcost
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true

      # This should go into custom primary image, here's only for the sake of explanation1
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Setup environment
          command: |
            mv config/database.ci.yml config/database.yml
            openssl aes-256-cbc -d -in .env.ci -out .env -k $KEY
            mv docker-compose.ci.yml docker-compose.yml
      - run:
          name: Build test containers
          command: |
            docker-compose build
      - run:
          name: Launch containers
          command: |
            docker-compose up -d
            sleep 10
      - run:
          name: Setup db and other stuff
          command: |
            docker-compose exec test bundle exec rake db:create db:migrate
      - run:
          name: Start tests
          command: |
            docker-compose exec test bundle exec test bundle-audit update && bundle exec bundle-audit check
            docker-compose exec test bundle exec rubocop
            docker-compose exec test bundle exec rails_best_practices .