# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f942e7cf20b0b2e2f0c5857fa4b74f40f31bb4a791be4d9d8961afecd65ae4e0df3e146e9b930adaad3fec58c0f17f701892ad0daa3bf43260ec87c9294b16b

test:
  secret_key_base: 86039f2d6259e4174742fa98fee22edebc7adfdb78e2e618e925cf1626c40faab7d4affabb23f02961c00b690fb27c04b179b1d8ebebb2cb2901300923d59978

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
